language: java
dist: xenial
env:
 global:
  - SONAR_TOKEN=99450b20c9fee3d54e02b007eb6f2729772048b5
jdk:
 - openjdk11
cache:
 directories:
  - $HOME/.m2/
addons:
 sonarcloud:
  organization: "vishalsonar"
before_script:
 - sudo touch /home/hind.json
 - sudo chmod 777 /home/hind.json
 - sudo echo $json >> /home/hind.json
 - sudo echo $json
script: mvn clean install sonar:sonar -Dsonar.projectKey=vishalsonar_hind -DskipTests=false -Dmaven.javadoc.skip=true -B -V
notification:
 email: vsonar908@gmail.com
